server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    sample: DEBUG

spring:
  thymeleaf:
    cache: false
  security:
